### ISSUE TITLE
Adding Data module

### ISSUE THREAD

**Issue by digitamo** [DJVUpp/android#2]
Add - Install - the Data module (viewer_module) to the view.

**Comment by digitamo** [comment]
# TODO :
- [x] Add the viewer module dependency.
- [ ] Open the book.
- [ ] show book pages in the application.

**Comment by digitamo** [comment]
## Problem statement :

Managed to add the module dependency to the android project, But since the core component [DjVuBean.java](https://github.com/DJVUpp/Desktop/blob/viewer_module/djuvpp-djvureader-windows-f4eb608c437c/DjVu%2B%2B%20viewer%20module/src/com/lizardtech/djvubean/DjVuBean.java#L66) inherits from [java.awt.Panel](https://docs.oracle.com/javase/7/docs/api/java/awt/Panel.html) and  java `swing` and `awt` are not supported by android compiler you'll always get an exception usually `java.lang.NoClassDefFoundError`.

#### Proposed solutions:
- Separate the view layer from the data layer entirely in the [viewer module](https://github.com/DJVUpp/Desktop/tree/viewer_module) from all classes and re-export the module, So basically it will not be called the viewer module.
- Discuss with the team members about new solutions.
